default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: Pasd!@#$12xzA12
  host: localhost

development:
  <<: *default
  database: ariana1

test:
  <<: *default
  database: ariana


production:
  <<: *default
  database: ariana
